import type { PlatformData } from "./types";

/**
 * Seeded preview data.
 *
 * No real financial records, no personal data beyond the two names given in
 * the brief, and nothing that belongs to the Stewardship Capital household
 * stewardship product. This exists so the workflow can be evaluated before the
 * architecture is approved and a real datastore is chosen.
 */
export const platformData: PlatformData = {
  people: [
    { id: "p-brooke", name: "Brooke Fox", role: "Event coordinator", organization: "Shine" },
    { id: "p-ryan", name: "Ryan Fox", role: "Emcee", organization: "Stewardship Capital" },
    { id: "p-megan", name: "Megan Ellis", role: "Operations lead", organization: "Shine" },
    { id: "p-sam", name: "Sam Okafor", role: "Hospitality host", organization: "Shine" },
    { id: "p-tori", name: "Tori Chen", role: "Design and print", organization: "Fox Print Studio" },
    { id: "p-dave", name: "Dave Lindquist", role: "Venue liaison", organization: "Northwoods Lodge" },
    { id: "p-lena", name: "Lena Ruiz", role: "Program lead", organization: "Redeemer Collective" },
  ],

  clients: [
    {
      id: "cl-shine",
      slug: "shine",
      name: "Shine",
      tagline: "A community of Christian founders learning to hold their companies with open hands.",
      theme: { accent: "#c2762c", accentSoft: "#f4e6d4", onAccent: "#ffffff" },
      people: [],
    },
    {
      id: "cl-redeemer",
      slug: "redeemer-collective",
      name: "Redeemer Collective",
      tagline: "Church planters and ministry leaders gathering for rest and direction.",
      theme: { accent: "#4a5aa8", accentSoft: "#e2e5f4", onAccent: "#ffffff" },
      people: [],
    },
  ],

  events: [
    {
      id: "ev-fw",
      clientId: "cl-shine",
      slug: "founders-weekend",
      name: "Founders Weekend",
      summary: "A long weekend at the lake for founders and their families.",
      cadence: "Annual, first weekend of October",
    },
    {
      id: "ev-lr",
      clientId: "cl-redeemer",
      slug: "leaders-retreat",
      name: "Leaders Retreat",
      summary: "Three days of rest, teaching, and planning for ministry leaders.",
      cadence: "Annual, spring",
    },
  ],

  editions: [
    {
      id: "ed-fw-2025",
      eventId: "ev-fw",
      slug: "2025",
      label: "Founders Weekend 2025",
      status: "complete",
      startDate: "2025-10-02",
      endDate: "2025-10-05",
      location: "Spooner, Wisconsin",
      venue: "Northwoods Lodge on Long Lake",
      budgetTotal: 48000,
      guestsExpected: 42,
      coordinatorId: "p-brooke",
      emceeId: "p-ryan",
      theme: {
        name: "Lakefront and fall",
        canopy: "#1d4034",
        water: "#12303c",
        ember: "#d8752f",
        bark: "#4a3626",
        mist: "#e8e2d4",
      },
      days: [
        { key: "thu", date: "2025-10-02", label: "Thursday", note: "Arrival and welcome." },
        { key: "fri", date: "2025-10-03", label: "Friday", note: "First program day." },
        { key: "sat", date: "2025-10-04", label: "Saturday", note: "Full day." },
        { key: "sun", date: "2025-10-05", label: "Sunday", note: "Sending and departure." },
      ],
    },
    {
      id: "ed-fw-2026",
      eventId: "ev-fw",
      slug: "2026",
      label: "Founders Weekend 2026",
      status: "planning",
      startDate: "2026-10-01",
      endDate: "2026-10-04",
      location: "Spooner, Wisconsin",
      venue: "Northwoods Lodge on Long Lake",
      budgetTotal: 60000,
      guestsExpected: 56,
      coordinatorId: "p-brooke",
      emceeId: "p-ryan",
      reusedFromEditionId: "ed-fw-2025",
      theme: {
        name: "Lakefront and fall",
        canopy: "#1d4034",
        water: "#12303c",
        ember: "#d8752f",
        bark: "#4a3626",
        mist: "#e8e2d4",
      },
      days: [
        { key: "thu", date: "2026-10-01", label: "Thursday", note: "Arrival, welcome dinner, and the opening bonfire." },
        { key: "fri", date: "2026-10-02", label: "Friday", note: "The first full program day." },
        { key: "sat", date: "2026-10-03", label: "Saturday", note: "The heart of the weekend." },
        { key: "sun", date: "2026-10-04", label: "Sunday", note: "Sending, departure, and pack up only." },
      ],
    },
    {
      id: "ed-lr-2027",
      eventId: "ev-lr",
      slug: "2027",
      label: "Leaders Retreat 2027",
      status: "planning",
      startDate: "2027-04-15",
      endDate: "2027-04-17",
      location: "Galena, Illinois",
      venue: "Bethel Retreat Center",
      budgetTotal: 22000,
      guestsExpected: 30,
      coordinatorId: "p-lena",
      emceeId: "p-lena",
      theme: {
        name: "Spring and chapel",
        canopy: "#2f3f6b",
        water: "#4a5aa8",
        ember: "#c98a3c",
        bark: "#3b3a52",
        mist: "#e6e6ef",
      },
      days: [
        { key: "thu", date: "2027-04-15", label: "Thursday", note: "Arrival and opening." },
        { key: "fri", date: "2027-04-16", label: "Friday", note: "Teaching and rest." },
        { key: "sat", date: "2027-04-17", label: "Saturday", note: "Planning and sending." },
      ],
    },
  ],

  sparks: [
    { id: "sp-01", editionId: "ed-fw-2026", title: "Sunrise pontoon prayer on Saturday", detail: "Optional, six thirty, no more than twelve people. Coffee on the boat.", category: "Experience", status: "captured", raisedBy: "Sam Okafor", raisedOn: "2026-08-11" },
    { id: "sp-02", editionId: "ed-fw-2026", title: "Hand written welcome note in every cabin", detail: "One note per household, staged before anyone arrives Thursday.", category: "Hospitality", status: "approved", raisedBy: "Brooke Fox", raisedOn: "2026-07-29", decision: "Approved. Brooke writes them, Megan stages the cabins Thursday morning.", decidedOn: "2026-08-04", builds: [ { kind: "budget", refId: "b-23", label: "Welcome notes and cabin baskets" }, { kind: "task", refId: "t-03", label: "Write and stage cabin welcome notes" }, { kind: "resource", refId: "r-07", label: "Cabin welcome baskets" } ] },
    { id: "sp-03", editionId: "ed-fw-2026", title: "Live acoustic set at the Saturday bonfire", detail: "Two hours, one guitar, nothing amplified past the tree line.", category: "Experience", status: "discussing", raisedBy: "Megan Ellis", raisedOn: "2026-08-06" },
    { id: "sp-04", editionId: "ed-fw-2026", title: "Founders wall with a one sentence legacy card", detail: "Every guest writes one sentence about what they want to steward well. The cards go on the wall and go home with them.", category: "Generosity", status: "approved", raisedBy: "Ryan Fox", raisedOn: "2026-07-22", decision: "Approved. Forty five minutes on Saturday before dinner.", decidedOn: "2026-08-04", builds: [ { kind: "schedule", refId: "sc-24", label: "Founders wall and legacy cards" }, { kind: "budget", refId: "b-22", label: "Legacy cards and founders wall" }, { kind: "task", refId: "t-05", label: "Design the founders wall and legacy cards" }, { kind: "runOfShow", refId: "cue-09", label: "Ryan explains the founders wall" } ] },
    { id: "sp-05", editionId: "ed-fw-2026", title: "Kids craft table during Friday sessions", detail: "Would let more parents attend both morning sessions.", category: "Hospitality", status: "parked", raisedBy: "Brooke Fox", raisedOn: "2026-07-18", decision: "Parked for 2027. Childcare licensing is not solved for this venue.", decidedOn: "2026-07-31" },
    { id: "sp-06", editionId: "ed-fw-2026", title: "Custom flannel blanket as the weekend gift", detail: "Shine label, given out Thursday so people actually use them at the fire.", category: "Generosity", status: "approved", raisedBy: "Tori Chen", raisedOn: "2026-07-15", decision: "Approved at sixty units. Order by the end of August to make the date.", decidedOn: "2026-08-18", builds: [ { kind: "budget", refId: "b-20", label: "Custom flannel blanket, sixty units" }, { kind: "task", refId: "t-07", label: "Place the flannel blanket order" }, { kind: "resource", refId: "r-05", label: "Custom flannel blankets" } ] },
    { id: "sp-07", editionId: "ed-fw-2026", title: "Late night pie bar on Friday", detail: "Local pies out at nine thirty. Low effort, high memory.", category: "Hospitality", status: "discussing", raisedBy: "Sam Okafor", raisedOn: "2026-08-12" },
    { id: "sp-08", editionId: "ed-fw-2026", title: "Shuttle from Minneapolis for out of state founders", detail: "Nine guests are flying in. A shuttle removes nine rental cars.", category: "Logistics", status: "captured", raisedBy: "Megan Ellis", raisedOn: "2026-08-14" },
    { id: "sp-09", editionId: "ed-fw-2026", title: "Saturday morning polar plunge", detail: "It would be memorable.", category: "Experience", status: "declined", raisedBy: "Ryan Fox", raisedOn: "2026-07-30", decision: "Declined. Water temperature and liability.", decidedOn: "2026-08-04" },
    { id: "sp-10", editionId: "ed-fw-2026", title: "Printed weekend field guide with schedule and map", detail: "Pocket sized. Schedule, map, house rules, and blank pages for notes.", category: "Communications", status: "approved", raisedBy: "Tori Chen", raisedOn: "2026-07-20", decision: "Approved. Print by the middle of September.", decidedOn: "2026-08-18", builds: [ { kind: "budget", refId: "b-21", label: "Printed weekend field guide" }, { kind: "task", refId: "t-06", label: "Lay out and print the weekend field guide" }, { kind: "resource", refId: "r-04", label: "Fox Print Studio" }, { kind: "guestComms", refId: "t-10", label: "Second guest email with travel details" } ] },
    { id: "sp-11", editionId: "ed-fw-2026", title: "Ryan opens each day with a three minute frame", detail: "Not a session. Three minutes to set the day and hand off.", category: "Program", status: "approved", raisedBy: "Brooke Fox", raisedOn: "2026-07-25", decision: "Approved. Ryan is emcee, not a speaker, so these stay at three minutes.", decidedOn: "2026-08-04", builds: [ { kind: "schedule", refId: "sc-11", label: "Friday morning frame" }, { kind: "schedule", refId: "sc-19", label: "Saturday morning frame" } ] },
    { id: "sp-12", editionId: "ed-fw-2026", title: "Local coffee roaster pour over bar on Saturday", detail: "Lakeside Coffee would staff it for the morning.", category: "Hospitality", status: "discussing", raisedBy: "Sam Okafor", raisedOn: "2026-08-13" },
    { id: "sp-13", editionId: "ed-fw-2026", title: "Photo book mailed thirty days after the weekend", detail: "Arrives after the glow fades, which is the point.", category: "Communications", status: "captured", raisedBy: "Tori Chen", raisedOn: "2026-08-15" },
    { id: "sp-14", editionId: "ed-fw-2026", title: "Sunday sending liturgy card for the drive home", detail: "One card per car. Something to read out loud on the way out.", category: "Generosity", status: "captured", raisedBy: "Ryan Fox", raisedOn: "2026-08-16" },

    { id: "sp-lr-01", editionId: "ed-lr-2027", title: "Silent morning before the first session", detail: "No phones, no talking, from wake up until breakfast ends.", category: "Program", status: "discussing", raisedBy: "Lena Ruiz", raisedOn: "2026-08-10" },
    { id: "sp-lr-02", editionId: "ed-lr-2027", title: "Spouses invited to Saturday only", detail: "Keeps the retreat focused but opens the closing day.", category: "Hospitality", status: "captured", raisedBy: "Lena Ruiz", raisedOn: "2026-08-12" },
    { id: "sp-lr-03", editionId: "ed-lr-2027", title: "Printed prayer guide for the year ahead", detail: "One per leader, dated for the twelve months after the retreat.", category: "Communications", status: "approved", raisedBy: "Lena Ruiz", raisedOn: "2026-08-01", decision: "Approved. Same printer as the Shine field guide.", decidedOn: "2026-08-15", builds: [{ kind: "budget", refId: "b-lr-05", label: "Printed prayer guide" }] },
  ],

  schedule: [
    { id: "sc-01", editionId: "ed-fw-2026", dayKey: "thu", start: "3:00 pm", end: "6:00 pm", title: "Cabin check in and arrivals", track: "Hospitality", location: "Lodge front porch", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-02", editionId: "ed-fw-2026", dayKey: "thu", start: "6:00 pm", end: "7:15 pm", title: "Welcome dinner", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-03", editionId: "ed-fw-2026", dayKey: "thu", start: "7:30 pm", end: "8:30 pm", title: "Opening welcome and weekend frame", track: "Program", location: "Great room", ownerId: "p-ryan", status: "confirmed", note: "Ryan emcees. There is no teaching session on Thursday." },
    { id: "sc-04", editionId: "ed-fw-2026", dayKey: "thu", start: "8:30 pm", end: "10:00 pm", title: "Lakefront bonfire and s'mores", track: "Experience", location: "Fire ring", ownerId: "p-sam", status: "confirmed" },

    { id: "sc-05", editionId: "ed-fw-2026", dayKey: "fri", start: "7:00 am", end: "8:30 am", title: "Coffee and breakfast", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-11", editionId: "ed-fw-2026", dayKey: "fri", start: "8:30 am", end: "8:45 am", title: "Morning frame", track: "Program", location: "Great room", ownerId: "p-ryan", status: "confirmed", sparkId: "sp-11", note: "Three minutes from the emcee, then hand off." },
    { id: "sc-06", editionId: "ed-fw-2026", dayKey: "fri", start: "8:45 am", end: "9:15 am", title: "Morning devotional", track: "Program", location: "Great room", ownerId: "p-brooke", status: "draft", note: "Still deciding who leads." },
    { id: "sc-07", editionId: "ed-fw-2026", dayKey: "fri", start: "9:15 am", end: "10:30 am", title: "Session one, founding with open hands", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-08", editionId: "ed-fw-2026", dayKey: "fri", start: "10:30 am", end: "11:00 am", title: "Break", track: "Meals", location: "Porch", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-09", editionId: "ed-fw-2026", dayKey: "fri", start: "11:00 am", end: "12:15 pm", title: "Roundtable, the hard number", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-10", editionId: "ed-fw-2026", dayKey: "fri", start: "12:15 pm", end: "1:30 pm", title: "Lunch", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-12", editionId: "ed-fw-2026", dayKey: "fri", start: "1:30 pm", end: "4:30 pm", title: "Open afternoon, pontoon, hiking, and rest", track: "Experience", location: "Long Lake", ownerId: "p-megan", status: "confirmed" },
    { id: "sc-13", editionId: "ed-fw-2026", dayKey: "fri", start: "4:30 pm", end: "5:30 pm", title: "Founder one on ones", track: "Program", location: "Cabins and dock", ownerId: "p-brooke", status: "draft", note: "Decision d-03 gates this." },
    { id: "sc-14", editionId: "ed-fw-2026", dayKey: "fri", start: "5:30 pm", end: "7:00 pm", title: "Dinner", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-15", editionId: "ed-fw-2026", dayKey: "fri", start: "7:00 pm", end: "8:15 pm", title: "Session two, stewardship at scale", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-16", editionId: "ed-fw-2026", dayKey: "fri", start: "8:15 pm", end: "10:00 pm", title: "Fire pit conversations", track: "Experience", location: "Fire ring", ownerId: "p-sam", status: "confirmed" },

    { id: "sc-17", editionId: "ed-fw-2026", dayKey: "sat", start: "7:00 am", end: "8:30 am", title: "Coffee and breakfast", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-19", editionId: "ed-fw-2026", dayKey: "sat", start: "8:30 am", end: "8:45 am", title: "Morning frame", track: "Program", location: "Great room", ownerId: "p-ryan", status: "confirmed", sparkId: "sp-11" },
    { id: "sc-18", editionId: "ed-fw-2026", dayKey: "sat", start: "8:45 am", end: "9:15 am", title: "Morning devotional", track: "Program", location: "Great room", ownerId: "p-brooke", status: "draft" },
    { id: "sc-20", editionId: "ed-fw-2026", dayKey: "sat", start: "9:15 am", end: "10:45 am", title: "Session three, the family table", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-21", editionId: "ed-fw-2026", dayKey: "sat", start: "10:45 am", end: "11:15 am", title: "Break", track: "Meals", location: "Porch", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-22", editionId: "ed-fw-2026", dayKey: "sat", start: "11:15 am", end: "12:30 pm", title: "Workshop, writing your stewardship statement", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-23", editionId: "ed-fw-2026", dayKey: "sat", start: "12:30 pm", end: "1:45 pm", title: "Lunch", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-25", editionId: "ed-fw-2026", dayKey: "sat", start: "1:45 pm", end: "4:00 pm", title: "Free afternoon, fishing and lake", track: "Experience", location: "Long Lake", ownerId: "p-megan", status: "confirmed" },
    { id: "sc-26", editionId: "ed-fw-2026", dayKey: "sat", start: "4:00 pm", end: "5:00 pm", title: "Family photos at the point", track: "Experience", location: "The point", ownerId: "p-tori", status: "draft" },
    { id: "sc-24", editionId: "ed-fw-2026", dayKey: "sat", start: "5:00 pm", end: "5:45 pm", title: "Founders wall and legacy cards", track: "Experience", location: "Great room", ownerId: "p-ryan", status: "confirmed", sparkId: "sp-04" },
    { id: "sc-27", editionId: "ed-fw-2026", dayKey: "sat", start: "5:45 pm", end: "7:15 pm", title: "Harvest dinner", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-28", editionId: "ed-fw-2026", dayKey: "sat", start: "7:15 pm", end: "8:45 pm", title: "Closing session and commissioning", track: "Program", location: "Great room", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-29", editionId: "ed-fw-2026", dayKey: "sat", start: "8:45 pm", end: "10:30 pm", title: "Bonfire, music, and testimony", track: "Experience", location: "Fire ring", ownerId: "p-megan", status: "confirmed" },

    { id: "sc-30", editionId: "ed-fw-2026", dayKey: "sun", start: "8:00 am", end: "9:15 am", title: "Breakfast and packing", track: "Meals", location: "Great room", ownerId: "p-sam", status: "confirmed" },
    { id: "sc-31", editionId: "ed-fw-2026", dayKey: "sun", start: "9:15 am", end: "10:00 am", title: "Sending and prayer", track: "Program", location: "Great room", ownerId: "p-ryan", status: "confirmed" },
    { id: "sc-32", editionId: "ed-fw-2026", dayKey: "sun", start: "10:00 am", end: "12:00 pm", title: "Departure", track: "Logistics", location: "Front drive", ownerId: "p-brooke", status: "confirmed" },
    { id: "sc-33", editionId: "ed-fw-2026", dayKey: "sun", start: "12:00 pm", end: "3:00 pm", title: "Pack up and venue walkthrough", track: "Logistics", location: "Whole property", ownerId: "p-dave", status: "confirmed", note: "Sunday is departure and pack up only. No program." },

    { id: "sc-lr-01", editionId: "ed-lr-2027", dayKey: "thu", start: "4:00 pm", end: "6:00 pm", title: "Arrival and check in", track: "Hospitality", location: "Main house", ownerId: "p-lena", status: "confirmed" },
    { id: "sc-lr-02", editionId: "ed-lr-2027", dayKey: "thu", start: "7:00 pm", end: "8:30 pm", title: "Opening dinner and introductions", track: "Meals", location: "Dining hall", ownerId: "p-lena", status: "confirmed" },
    { id: "sc-lr-03", editionId: "ed-lr-2027", dayKey: "fri", start: "9:00 am", end: "11:00 am", title: "Teaching, the long obedience", track: "Program", location: "Chapel", ownerId: "p-lena", status: "draft" },
    { id: "sc-lr-04", editionId: "ed-lr-2027", dayKey: "fri", start: "1:00 pm", end: "5:00 pm", title: "Rest, walking, and spiritual direction", track: "Experience", location: "Grounds", ownerId: "p-lena", status: "confirmed" },
    { id: "sc-lr-05", editionId: "ed-lr-2027", dayKey: "sat", start: "9:00 am", end: "12:00 pm", title: "Year ahead planning", track: "Program", location: "Chapel", ownerId: "p-lena", status: "draft" },
    { id: "sc-lr-06", editionId: "ed-lr-2027", dayKey: "sat", start: "1:00 pm", end: "2:00 pm", title: "Sending and departure", track: "Logistics", location: "Front drive", ownerId: "p-lena", status: "confirmed" },
  ],

  budget: [
    { id: "b-01", editionId: "ed-fw-2026", category: "Venue and lodging", label: "Northwoods Lodge, three nights, full property", planned: 18000, committed: 18000, actual: 9000, ownerId: "p-dave", vendorId: "r-01" },
    { id: "b-02", editionId: "ed-fw-2026", category: "Venue and lodging", label: "Six lakeside cabins", planned: 4800, committed: 4800, actual: 2400, ownerId: "p-dave", vendorId: "r-01" },
    { id: "b-03", editionId: "ed-fw-2026", category: "Venue and lodging", label: "Cleaning and damage deposit", planned: 1200, committed: 1200, actual: 0, ownerId: "p-dave" },
    { id: "b-04", editionId: "ed-fw-2026", category: "Food and beverage", label: "Thursday welcome dinner", planned: 2400, committed: 2400, actual: 600, ownerId: "p-sam", vendorId: "r-02" },
    { id: "b-05", editionId: "ed-fw-2026", category: "Food and beverage", label: "Friday meals, all day", planned: 3600, committed: 3600, actual: 0, ownerId: "p-sam", vendorId: "r-02" },
    { id: "b-06", editionId: "ed-fw-2026", category: "Food and beverage", label: "Saturday meals, all day", planned: 3900, committed: 3200, actual: 0, ownerId: "p-sam", vendorId: "r-02" },
    { id: "b-07", editionId: "ed-fw-2026", category: "Food and beverage", label: "Sunday breakfast", planned: 1100, committed: 0, actual: 0, ownerId: "p-sam" },
    { id: "b-08", editionId: "ed-fw-2026", category: "Food and beverage", label: "Coffee, snacks, and fire pit s'mores", planned: 1400, committed: 0, actual: 0, ownerId: "p-sam" },
    { id: "b-09", editionId: "ed-fw-2026", category: "Food and beverage", label: "Dietary accommodations", planned: 1100, committed: 0, actual: 0, ownerId: "p-sam" },
    { id: "b-10", editionId: "ed-fw-2026", category: "Program and speakers", label: "Guest speaker honorarium, two sessions", planned: 4000, committed: 4000, actual: 2000, ownerId: "p-brooke" },
    { id: "b-11", editionId: "ed-fw-2026", category: "Program and speakers", label: "Speaker travel and lodging", planned: 1800, committed: 1000, actual: 0, ownerId: "p-brooke" },
    { id: "b-12", editionId: "ed-fw-2026", category: "Program and speakers", label: "Workshop materials", planned: 900, committed: 0, actual: 0, ownerId: "p-tori" },
    { id: "b-13", editionId: "ed-fw-2026", category: "Program and speakers", label: "Devotional guide licensing", planned: 800, committed: 0, actual: 0, ownerId: "p-brooke" },
    { id: "b-14", editionId: "ed-fw-2026", category: "Experience", label: "Pontoon and boat rental, two days", planned: 1600, committed: 1600, actual: 800, ownerId: "p-megan" },
    { id: "b-15", editionId: "ed-fw-2026", category: "Experience", label: "Bonfire wood, chairs, and lighting", planned: 900, committed: 550, actual: 0, ownerId: "p-megan", vendorId: "r-06" },
    { id: "b-16", editionId: "ed-fw-2026", category: "Experience", label: "Saturday live acoustic set", planned: 1200, committed: 0, actual: 0, ownerId: "p-megan", sparkId: "sp-03" },
    { id: "b-17", editionId: "ed-fw-2026", category: "Experience", label: "Fishing guides and gear", planned: 1100, committed: 0, actual: 0, ownerId: "p-megan" },
    { id: "b-18", editionId: "ed-fw-2026", category: "Production and AV", label: "Sound system, mics, and operator", planned: 2200, committed: 1800, actual: 900, ownerId: "p-megan", vendorId: "r-03" },
    { id: "b-19", editionId: "ed-fw-2026", category: "Production and AV", label: "Lighting for the lodge great room", planned: 1000, committed: 0, actual: 0, ownerId: "p-megan" },
    { id: "b-20", editionId: "ed-fw-2026", category: "Gifts and print", label: "Custom flannel blanket, sixty units", planned: 1800, committed: 0, actual: 0, ownerId: "p-tori", sparkId: "sp-06" },
    { id: "b-21", editionId: "ed-fw-2026", category: "Gifts and print", label: "Printed weekend field guide", planned: 900, committed: 640, actual: 0, ownerId: "p-tori", vendorId: "r-04", sparkId: "sp-10" },
    { id: "b-22", editionId: "ed-fw-2026", category: "Gifts and print", label: "Legacy cards and founders wall", planned: 500, committed: 350, actual: 0, ownerId: "p-tori", vendorId: "r-04", sparkId: "sp-04" },
    { id: "b-23", editionId: "ed-fw-2026", category: "Gifts and print", label: "Welcome notes and cabin baskets", planned: 400, committed: 250, actual: 0, ownerId: "p-brooke", sparkId: "sp-02" },
    { id: "b-24", editionId: "ed-fw-2026", category: "Travel", label: "Airport shuttle, Minneapolis", planned: 1600, committed: 0, actual: 0, ownerId: "p-megan", sparkId: "sp-08" },
    { id: "b-25", editionId: "ed-fw-2026", category: "Travel", label: "Local transport and fuel", planned: 800, committed: 0, actual: 0, ownerId: "p-megan" },
    { id: "b-26", editionId: "ed-fw-2026", category: "Contingency", label: "Weather and overflow contingency", planned: 1000, committed: 0, actual: 0, ownerId: "p-brooke" },

    { id: "b25-01", editionId: "ed-fw-2025", category: "Venue and lodging", label: "Northwoods Lodge and cabins", planned: 20000, committed: 20000, actual: 18000, ownerId: "p-dave" },
    { id: "b25-02", editionId: "ed-fw-2025", category: "Food and beverage", label: "All meals, forty two guests", planned: 11500, committed: 11500, actual: 13600, ownerId: "p-sam" },
    { id: "b25-03", editionId: "ed-fw-2025", category: "Program and speakers", label: "Speaker honorarium and travel", planned: 6200, committed: 6200, actual: 6200, ownerId: "p-brooke" },
    { id: "b25-04", editionId: "ed-fw-2025", category: "Experience", label: "Boats, fire, and fishing", planned: 4000, committed: 4000, actual: 3720, ownerId: "p-megan" },
    { id: "b25-05", editionId: "ed-fw-2025", category: "Production and AV", label: "Sound and lighting", planned: 2400, committed: 2400, actual: 1900, ownerId: "p-megan" },
    { id: "b25-06", editionId: "ed-fw-2025", category: "Gifts and print", label: "Gifts and printed guide", planned: 2400, committed: 2400, actual: 1660, ownerId: "p-tori" },
    { id: "b25-07", editionId: "ed-fw-2025", category: "Travel", label: "Local transport", planned: 1000, committed: 1000, actual: 1200, ownerId: "p-megan" },
    { id: "b25-08", editionId: "ed-fw-2025", category: "Contingency", label: "Contingency, unused", planned: 500, committed: 0, actual: 0, ownerId: "p-brooke" },

    { id: "b-lr-01", editionId: "ed-lr-2027", category: "Venue and lodging", label: "Bethel Retreat Center, two nights", planned: 9600, committed: 9600, actual: 0, ownerId: "p-lena" },
    { id: "b-lr-02", editionId: "ed-lr-2027", category: "Food and beverage", label: "All meals, thirty guests", planned: 6400, committed: 0, actual: 0, ownerId: "p-lena" },
    { id: "b-lr-03", editionId: "ed-lr-2027", category: "Program and speakers", label: "Teaching honorarium", planned: 3000, committed: 0, actual: 0, ownerId: "p-lena" },
    { id: "b-lr-04", editionId: "ed-lr-2027", category: "Experience", label: "Spiritual direction sessions", planned: 1800, committed: 0, actual: 0, ownerId: "p-lena" },
    { id: "b-lr-05", editionId: "ed-lr-2027", category: "Gifts and print", label: "Printed prayer guide", planned: 1200, committed: 0, actual: 0, ownerId: "p-lena", sparkId: "sp-lr-03" },
  ],

  tasks: [
    { id: "t-01", editionId: "ed-fw-2026", title: "Confirm the final guest count with the lodge", ownerId: "p-brooke", due: "2026-09-04", status: "doing", area: "Logistics" },
    { id: "t-02", editionId: "ed-fw-2026", title: "Lock the Saturday dinner menu with Spooner Provisions", ownerId: "p-sam", due: "2026-08-28", status: "todo", area: "Hospitality" },
    { id: "t-03", editionId: "ed-fw-2026", title: "Write and stage cabin welcome notes", ownerId: "p-brooke", due: "2026-09-25", status: "todo", area: "Hospitality", sparkId: "sp-02" },
    { id: "t-04", editionId: "ed-fw-2026", title: "Book the sound operator for both program days", ownerId: "p-megan", due: "2026-09-01", status: "blocked", area: "Logistics" },
    { id: "t-05", editionId: "ed-fw-2026", title: "Design the founders wall and legacy cards", ownerId: "p-tori", due: "2026-09-11", status: "doing", area: "Generosity", sparkId: "sp-04" },
    { id: "t-06", editionId: "ed-fw-2026", title: "Lay out and print the weekend field guide", ownerId: "p-tori", due: "2026-09-18", status: "todo", area: "Communications", sparkId: "sp-10" },
    { id: "t-07", editionId: "ed-fw-2026", title: "Place the flannel blanket order, sixty units", ownerId: "p-tori", due: "2026-08-31", status: "todo", area: "Generosity", sparkId: "sp-06" },
    { id: "t-08", editionId: "ed-fw-2026", title: "Confirm pontoon rental dates", ownerId: "p-megan", due: "2026-08-24", status: "done", area: "Logistics" },
    { id: "t-09", editionId: "ed-fw-2026", title: "Collect dietary needs from the guest form", ownerId: "p-sam", due: "2026-09-08", status: "todo", area: "Hospitality" },
    { id: "t-10", editionId: "ed-fw-2026", title: "Send the second guest email with travel details", ownerId: "p-brooke", due: "2026-09-02", status: "todo", area: "Communications" },
    { id: "t-11", editionId: "ed-fw-2026", title: "Walk the property with Dave and mark the fire ring", ownerId: "p-megan", due: "2026-09-19", status: "todo", area: "Logistics" },
    { id: "t-12", editionId: "ed-fw-2026", title: "Draft the run of show for both program days", ownerId: "p-brooke", due: "2026-09-12", status: "doing", area: "Program" },
    { id: "t-13", editionId: "ed-fw-2026", title: "Confirm speaker travel and lodging", ownerId: "p-brooke", due: "2026-08-26", status: "doing", area: "Program" },
    { id: "t-14", editionId: "ed-fw-2026", title: "Build the Sunday pack up checklist", ownerId: "p-dave", due: "2026-10-01", status: "todo", area: "Logistics" },

    { id: "t-lr-01", editionId: "ed-lr-2027", title: "Hold the retreat center for April 2027", ownerId: "p-lena", due: "2026-09-30", status: "done", area: "Logistics" },
    { id: "t-lr-02", editionId: "ed-lr-2027", title: "Invite the teaching guest", ownerId: "p-lena", due: "2026-11-14", status: "todo", area: "Program" },
    { id: "t-lr-03", editionId: "ed-lr-2027", title: "Open registration to the leader list", ownerId: "p-lena", due: "2026-12-05", status: "todo", area: "Communications" },
  ],

  resources: [
    { id: "r-01", editionId: "ed-fw-2026", kind: "vendor", name: "Northwoods Lodge", detail: "Full property and six cabins, three nights on Long Lake.", ownerId: "p-dave", status: "confirmed" },
    { id: "r-02", editionId: "ed-fw-2026", kind: "vendor", name: "Spooner Provisions Catering", detail: "All meals Thursday through Sunday.", ownerId: "p-sam", status: "holding" },
    { id: "r-03", editionId: "ed-fw-2026", kind: "vendor", name: "Timber and Tone Audio", detail: "Sound system, mics, and an operator for both program days.", ownerId: "p-megan", status: "needed" },
    { id: "r-04", editionId: "ed-fw-2026", kind: "vendor", name: "Fox Print Studio", detail: "Field guide, legacy cards, and signage.", ownerId: "p-tori", status: "confirmed", sparkId: "sp-10" },
    { id: "r-05", editionId: "ed-fw-2026", kind: "supply", name: "Custom flannel blankets", detail: "Shine label, handed out Thursday at check in.", ownerId: "p-tori", status: "needed", quantity: "60 units", sparkId: "sp-06" },
    { id: "r-06", editionId: "ed-fw-2026", kind: "supply", name: "Fire wood and fire ring seating", detail: "Delivered Thursday morning and restocked Saturday.", ownerId: "p-megan", status: "holding", quantity: "4 cords, 30 chairs" },
    { id: "r-07", editionId: "ed-fw-2026", kind: "supply", name: "Cabin welcome baskets", detail: "Hand written note, water, snacks, and a map.", ownerId: "p-brooke", status: "needed", quantity: "26 baskets", sparkId: "sp-02" },
    { id: "r-08", editionId: "ed-fw-2026", kind: "vendor", name: "Lakeside Coffee Co.", detail: "Saturday morning pour over bar. Still under discussion.", ownerId: "p-sam", status: "needed", sparkId: "sp-12" },

    { id: "r-lr-01", editionId: "ed-lr-2027", kind: "vendor", name: "Bethel Retreat Center", detail: "Lodging, chapel, and dining for thirty.", ownerId: "p-lena", status: "confirmed" },
    { id: "r-lr-02", editionId: "ed-lr-2027", kind: "supply", name: "Printed prayer guides", detail: "One per leader, dated for the year ahead.", ownerId: "p-lena", status: "needed", quantity: "30 units", sparkId: "sp-lr-03" },
  ],

  cues: [
    { id: "cue-01", editionId: "ed-fw-2026", scheduleItemId: "sc-03", at: "7:30 pm", cue: "House lights down, walk in music fades", whoId: "p-megan" },
    { id: "cue-02", editionId: "ed-fw-2026", scheduleItemId: "sc-03", at: "7:32 pm", cue: "Ryan opens, three minutes, welcome and the weekend frame", whoId: "p-ryan" },
    { id: "cue-03", editionId: "ed-fw-2026", scheduleItemId: "sc-03", at: "7:36 pm", cue: "Brooke covers cabins, meals, and quiet hours", whoId: "p-brooke" },
    { id: "cue-04", editionId: "ed-fw-2026", scheduleItemId: "sc-03", at: "7:45 pm", cue: "Table introductions, two minutes each", whoId: "p-ryan" },
    { id: "cue-05", editionId: "ed-fw-2026", scheduleItemId: "sc-07", at: "9:15 am", cue: "Ryan introduces the speaker, ninety seconds", whoId: "p-ryan" },
    { id: "cue-06", editionId: "ed-fw-2026", scheduleItemId: "sc-07", at: "9:17 am", cue: "Session one begins, mic check already confirmed", whoId: "p-megan" },
    { id: "cue-07", editionId: "ed-fw-2026", scheduleItemId: "sc-07", at: "10:20 am", cue: "Ten minute warning to the speaker", whoId: "p-megan" },
    { id: "cue-08", editionId: "ed-fw-2026", scheduleItemId: "sc-24", at: "5:00 pm", cue: "Cards and pens already on every table", whoId: "p-tori" },
    { id: "cue-09", editionId: "ed-fw-2026", scheduleItemId: "sc-24", at: "5:05 pm", cue: "Ryan explains the founders wall, two minutes", whoId: "p-ryan" },
    { id: "cue-10", editionId: "ed-fw-2026", scheduleItemId: "sc-24", at: "5:20 pm", cue: "Guests post cards, music underneath", whoId: "p-megan" },
    { id: "cue-11", editionId: "ed-fw-2026", scheduleItemId: "sc-28", at: "7:15 pm", cue: "Lights to warm, fire lit outside", whoId: "p-megan" },
    { id: "cue-12", editionId: "ed-fw-2026", scheduleItemId: "sc-28", at: "8:30 pm", cue: "Commissioning, everyone stands", whoId: "p-brooke" },
  ],

  decisions: [
    { id: "d-01", editionId: "ed-fw-2026", question: "Do we add a live acoustic set on Saturday night?", context: "Spark sp-03. A budget line exists at 1,200 dollars and is not committed.", ownerId: "p-megan", status: "open", needsBy: "2026-08-28", sparkId: "sp-03" },
    { id: "d-02", editionId: "ed-fw-2026", question: "Do we run an airport shuttle from Minneapolis?", context: "Nine guests are flying. Travel has 1,600 dollars planned and nothing committed.", ownerId: "p-brooke", status: "open", needsBy: "2026-09-04", sparkId: "sp-08" },
    { id: "d-03", editionId: "ed-fw-2026", question: "Is Friday afternoon fully open, or do we schedule one on ones?", context: "Schedule item sc-13 is still draft and blocks the field guide print date.", ownerId: "p-brooke", status: "open", needsBy: "2026-08-28" },
    { id: "d-04", editionId: "ed-fw-2026", question: "Do we add the Saturday pour over bar?", context: "Spark sp-12. Adds about 700 dollars and one more vendor to manage.", ownerId: "p-sam", status: "deferred", needsBy: "2026-09-11", sparkId: "sp-12" },
    { id: "d-05", editionId: "ed-fw-2026", question: "Blanket or field guide as the primary gift?", context: "Gift budget is capped at 3,600 dollars.", ownerId: "p-tori", status: "decided", outcome: "Both. The blanket is the gift and the field guide is a tool. Gift spend stays at 3,600.", needsBy: "2026-08-14" },
    { id: "d-06", editionId: "ed-fw-2026", question: "Is there any Sunday programming?", context: "Several people asked for a Sunday morning session.", ownerId: "p-brooke", status: "decided", outcome: "No. Sunday is sending, departure, and pack up only.", needsBy: "2026-08-07" },

    { id: "d-lr-01", editionId: "ed-lr-2027", question: "Are spouses invited for Saturday?", context: "Spark sp-lr-02. Changes the meal count and the closing session.", ownerId: "p-lena", status: "open", needsBy: "2026-10-30", sparkId: "sp-lr-02" },
  ],

  meetings: [
    { id: "m-01", editionId: "ed-fw-2026", meetingOn: "2026-08-25", title: "Weekly planning, August 25", sparkIds: ["sp-03", "sp-07", "sp-12"], decisionIds: ["d-01", "d-03"], note: "Thirty minutes. Sparks first, then the two decisions that gate budget." },
    { id: "m-02", editionId: "ed-fw-2026", meetingOn: "2026-08-18", title: "Weekly planning, August 18", sparkIds: ["sp-06", "sp-10"], decisionIds: ["d-05"], note: "Gift decision closed. Both sparks approved and moved to build." },
    { id: "m-lr-01", editionId: "ed-lr-2027", meetingOn: "2026-08-27", title: "Monthly planning, August 27", sparkIds: ["sp-lr-01", "sp-lr-02"], decisionIds: ["d-lr-01"], note: "Early planning cadence. Monthly until January, then weekly." },
  ],

  reviews: [
    {
      id: "rev-2025",
      editionId: "ed-fw-2025",
      state: "complete",
      headline: "Forty two founders at the lake, and a weekend most of them still bring up.",
      attended: 42,
      spendActual: 46280,
      sections: [
        { heading: "What worked", entries: ["The Thursday bonfire did more relational work than any session.", "Open Friday afternoon was the single most requested thing to keep.", "One venue for lodging, meals, and program removed almost all transport."] },
        { heading: "What did not", entries: ["Saturday ran forty minutes long and pushed dinner.", "Sound was under specified for the great room.", "Dietary needs were collected too late to plan around."] },
        { heading: "What it cost", entries: ["Came in 1,720 dollars under a 48,000 dollar budget.", "Food ran over by 2,100 dollars because of the late headcount.", "Gifts came in under because the print order was combined."] },
      ],
      carryForward: [
        "Keep Friday afternoon completely open.",
        "Book a real sound operator, not a volunteer.",
        "Collect dietary needs at registration, not two weeks out.",
        "Hold Saturday to a hard stop before dinner.",
        "Combine every print order into one run.",
      ],
    },
    {
      id: "rev-2026",
      editionId: "ed-fw-2026",
      state: "prepared",
      headline: "Prepared before the weekend, so the review is not written from memory afterward.",
      sections: [
        { heading: "What to watch", entries: ["Does the hard stop before Saturday dinner actually hold?", "Does the field guide reduce the number of schedule questions?", "Do the flannel blankets get used at the fire, or left in cabins?"] },
        { heading: "Carried in from 2025", entries: ["Friday afternoon is open and protected.", "Sound operator is a budgeted line, not a volunteer ask.", "Dietary needs are collected on the registration form.", "Print is one combined order through Fox Print Studio."] },
        { heading: "Open at the time of writing", entries: ["Saturday acoustic set is undecided.", "Airport shuttle is undecided.", "Friday one on ones are still draft."] },
      ],
      carryForward: [],
    },
    {
      id: "rev-lr-2027",
      editionId: "ed-lr-2027",
      state: "prepared",
      headline: "First edition. Nothing to carry forward yet.",
      sections: [
        { heading: "What to watch", entries: ["Does the silent morning hold for a group this size?", "Is two nights long enough for real rest?"] },
      ],
      carryForward: [],
    },
  ],
};
