-- The five master calendar days, as the one source every view reads.
--
-- Wednesday September 30 to Sunday October 4, 2026. Rows that already existed
-- keep their id and their guest copy, so menus and activity detail survive the
-- import; rows the master supersedes are copied into schedule_items_archive
-- before they leave the working views, so nothing is lost.
--
-- Every row carries its lead, assigned team, what happens, setup notes, and
-- whether it is Program or Operations. The run of show, the volunteer duties, a
-- person's own schedule and the guest schedule are then four readings of the
-- same records rather than three copies that drift apart.
--
-- Volunteer duties are the Operations rows, one task each, linked back to the
-- row it came from. Pre-event tasks are left exactly as they are.

create table if not exists public.schedule_items_archive (
  id uuid primary key,
  engagement_id uuid not null references public.engagements (id) on delete cascade,
  snapshot jsonb not null,
  archived_at timestamptz not null default now()
);

alter table public.schedule_items_archive enable row level security;

drop policy if exists schedule_items_archive_select_staff on public.schedule_items_archive;
create policy schedule_items_archive_select_staff
  on public.schedule_items_archive for select
  using (public.is_platform_staff());

revoke all on public.schedule_items_archive from anon;

do $migration$
declare
  shine constant uuid := 'c4c371a6-6378-4f80-9d78-f9a6359ae8db';
  expected integer;
  found integer;
begin

create temporary table master (
  id uuid primary key, day_key text, starts_label text, ends_label text,
  title text, track text, audience text, daypart text, guest_guide jsonb,
  ops jsonb, position integer, is_duty boolean
) on commit drop;

insert into master values
  ('f18fcb33-6c73-5569-8ebc-15d7811d0f02'::uuid, $q$wed$q$, $q$6:00 pm$q$, null, $q$Early team arrival and property prayer$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Arrive, settle in, pray over the property, and begin room preparation.", "owner": "Brooke", "support": "Early-arrival team", "category": "operations", "materials": "Keys, arrival list, prayer guide", "confirm": "time"}$q$::jsonb, 0, true),
  ('b0c56b80-a8c5-4da0-a124-ba5bd275eb6d'::uuid, $q$wed$q$, $q$6:00 pm$q$, $q$6:30 pm$q$, $q$Full setup team arrival and huddle$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Unload trailer, tour work areas, confirm room assignments, and divide setup zones.", "owner": "Brooke", "support": "Alice, Mike, Scott, Keta, Emma, Wanyonyi family", "category": "operations", "materials": "Setup checklist, carts, labels"}$q$::jsonb, 1, true),
  ('008abd90-6694-5d25-8ee3-b484e1e754bf'::uuid, $q$wed$q$, $q$6:30 pm$q$, $q$7:00 pm$q$, $q$Room assignments and setup$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Walk every room and finalize sleeping arrangements, linens, place signs.", "owner": "Brooke", "support": "Wanyonyi family and Mike", "category": "operations", "materials": "Room list, signs, linens", "notes": "Complete by end of day."}$q$::jsonb, 2, true),
  ('e2fb2b50-4d78-5a53-b728-865e475ddfa0'::uuid, $q$wed$q$, $q$7:00 pm$q$, $q$7:30 pm$q$, $q$Cook and prepare team dinner$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Prepare burgers, brats, sides, cider, and Keta's birthday surprise.", "owner": "Keta and Emma", "support": "Keta and Emma", "category": "operations", "materials": "Dinner supplies, cake, cider"}$q$::jsonb, 3, true),
  ('aaf51f00-fd53-4d15-8bf1-9aab0fcb858b'::uuid, $q$wed$q$, $q$7:30 pm$q$, $q$8:00 pm$q$, $q$Team dinner and birthday celebration$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Eat together, celebrate Keta, review Thursday priorities, and close setup for the night.", "owner": "Brooke", "support": "Ryan, Alice, Mike, Scott, Keta, Wanyonyi family", "category": "operations", "notes": "Brooke will discuss Thursday priorities."}$q$::jsonb, 4, true),
  ('583e5bf6-aee2-5e46-95d2-ec8c7a4d05b5'::uuid, $q$thu$q$, $q$7:30 am$q$, $q$8:00 am$q$, $q$Breakfast$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Yogurt and granola.", "owner": "Mike", "support": "Full team", "category": "operations"}$q$::jsonb, 5, true),
  ('629c15d8-ae61-5296-b4e3-54d4f7809250'::uuid, $q$thu$q$, $q$8:00 am$q$, $q$8:30 am$q$, $q$Team devotional and prayer$q$, $q$Program$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Center the team spiritually and pray over guests, speakers, worship, and the weekend.", "owner": "Tito", "support": "Full team", "category": "program", "materials": "Bible, prayer prompts", "notes": "The source lists the lead as “Tito?”.", "confirm": "assignment"}$q$::jsonb, 6, false),
  ('c620dd1c-d2f3-59d9-ba21-da70c1c8bbac'::uuid, $q$thu$q$, $q$8:30 am$q$, $q$10:00 am$q$, $q$Guest-room and arrival setup$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Assemble room gifts and bathroom baskets; set check-in table and table displays.", "owner": "Brooke", "support": "Ryan, Brooke, Keta, Emma", "category": "operations", "materials": "Room presents, baskets, check-in supplies"}$q$::jsonb, 7, true),
  ('0315506e-35e8-5aae-8eee-ec5d1a5b971d'::uuid, $q$thu$q$, $q$8:30 am$q$, $q$10:00 am$q$, $q$Balloon arch and flower vases$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Build arrival visuals and place finished arrangements.", "owner": "Brooke", "support": "Scott, Brooke and Keta", "category": "operations", "materials": "Balloons, frame, flowers, vases"}$q$::jsonb, 8, true),
  ('256343dd-563f-587c-9050-2a0acd94df2e'::uuid, $q$thu$q$, $q$9:00 am$q$, $q$10:00 am$q$, $q$Illustration preparation$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Cut rope, finish four-sided stakes, stage two tents, and confirm display locations.", "owner": "Ryan", "support": "Scott and Mike", "category": "operations", "materials": "Rope, scissors, stakes, Sharpies, two tents, sign", "notes": "Verse and SHINE prepared on stakes; response and name sides blank."}$q$::jsonb, 9, true),
  ('f8de9e71-23cb-5f85-bcc3-67f03250f3a5'::uuid, $q$thu$q$, $q$10:00 am$q$, $q$11:00 am$q$, $q$Coffee, snack and outdoor hospitality setup$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Build coffee and snack stations; place outdoor candles and jars, scope out activity locations.", "owner": "Brooke", "support": "Ryan, Emma, Brooke and Keta", "category": "operations", "materials": "Espresso supplies, snacks, candles, jars", "notes": "Keep snack station stocked throughout weekend."}$q$::jsonb, 10, true),
  ('3dec38d3-a116-563e-ac30-b846dbe6b88c'::uuid, $q$thu$q$, $q$10:30 am$q$, $q$12:00 pm$q$, $q$Audio visual and speaker setup$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Set speakers, microphones, video playback, slides, lighting, and backup files.", "owner": "Junior", "support": "Junior and Scott", "category": "operations", "materials": "Speakers, microphones, laptop, cables, backup files", "notes": "Junior owns AV; Scott owns speaker setup."}$q$::jsonb, 11, true),
  ('94bd3e12-ffbf-57e3-a381-a284433c7dd1'::uuid, $q$thu$q$, $q$12:00 pm$q$, $q$1:00 pm$q$, $q$Team lunch and progress check$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Eat, review unfinished work, and reassign gaps.", "owner": "Brooke", "support": "Full team", "category": "operations", "materials": "Lunch, checklist"}$q$::jsonb, 12, true),
  ('d249a3a2-b4ae-5288-9ab0-bf9ce756243a'::uuid, $q$thu$q$, $q$1:00 pm$q$, $q$2:30 pm$q$, $q$Final property setup$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Finish guest rooms, hospitality areas, signage, tables, and exterior details.", "owner": "Brooke", "support": "Full team", "category": "operations", "materials": "Review setup checklist"}$q$::jsonb, 13, true),
  ('0a6468a7-4928-5b58-b7d1-bb760622506e'::uuid, $q$thu$q$, $q$2:30 pm$q$, $q$3:15 pm$q$, $q$Illustration and program rehearsal$q$, $q$Program$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Practice Build the Tent, worship handoff, speaker introduction, AV cues, and placement of props.", "owner": "Mike and Ryan", "support": "Mike, Ryan, Brooke, JonCarlos, Junior and Scott", "category": "program", "materials": "Tents, timer, microphones, music, slides", "notes": "Leave one or both completed tents displayed after the challenge."}$q$::jsonb, 14, false),
  ('94d3501a-4879-5272-9ef7-3e0ef07f71e9'::uuid, $q$thu$q$, $q$3:15 pm$q$, $q$4:00 pm$q$, $q$Final walkthrough and team reset$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Check rooms, bathrooms, entry, light candles, turn on music and AV, discuss arrival positions; team changes clothes.", "owner": "Brooke", "support": "Full team", "category": "operations", "materials": "Final checklist", "notes": "All setup must be guest-ready by 4:00 PM."}$q$::jsonb, 15, true),
  ('920b31de-4366-420a-a0f5-959e7d80459a'::uuid, $q$thu$q$, $q$4:00 pm$q$, $q$5:00 pm$q$, $q$Guest arrival, bellhop and room tours$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "arrival", "summary": "Welcome, help with luggage and a tour of the house.", "title": "Guest arrival and room tours"}$q$::jsonb, $q${"purpose": "Welcome guests, unload luggage, complete check-in, name tags, and orient guests to the house.", "owner": "Brooke", "support": "Ryan, Brooke and Junior", "category": "operations", "materials": "Check-in table, room list, welcome gifts", "notes": "Arrival may continue through dinner; Junior captures key moments."}$q$::jsonb, 16, true),
  ('a0340a48-b882-46dc-935c-87feda90ebb6'::uuid, $q$thu$q$, $q$4:00 pm$q$, $q$6:00 pm$q$, $q$Bible character name game$q$, $q$Program$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "game", "summary": "Laugh, connect and learn names.", "title": "Ice breaker: Bible character name game"}$q$::jsonb, $q${"purpose": "Help guests connect and learn names through the opening icebreaker.", "owner": "Ryan", "support": "Emma prepares; full group participates", "category": "program", "materials": "Printed character name tags"}$q$::jsonb, 17, false),
  ('b1f0a5d2-0f4a-4b1e-9c1a-2d5f3a7c9102'::uuid, $q$thu$q$, $q$4:00 pm$q$, $q$6:30 pm$q$, $q$Welcome appetizers and dessert$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "meal", "menu": ["Smoked burnt ends", "Warm popovers with strawberry compote butter", "House-made cheesy jalapeño dip and tortilla chips", "Brownies", "Pork hot link slices", "Chicken skewers"], "summary": "A warm, informal opening meal.", "title": "Appetizers and dessert"}$q$::jsonb, $q${"purpose": "Serve catered appetizers and create a warm, informal opening meal.", "owner": "Brooke", "support": "Hospitality team", "category": "operations", "materials": "Catered food, plates, drinks", "notes": "Snack station remains stocked."}$q$::jsonb, 18, true),
  ('db5dcd8d-d853-45ac-aadf-279c0e50198a'::uuid, $q$thu$q$, $q$6:30 pm$q$, $q$6:50 pm$q$, $q$Meal cleanup and worship reset$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "break", "title": "Get ready for worship", "summary": "Clear food, clean dining areas, reset seating, and complete final microphone check."}$q$::jsonb, $q${"purpose": "Clear food, clean dining areas, reset seating, and complete final microphone check.", "owner": "Keta", "support": "Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup supplies, AV checklist", "notes": "Mike and tent props ready by 6:45 PM."}$q$::jsonb, 19, true),
  ('74e88a66-bbbf-54d6-9d69-c26d8e48baba'::uuid, $q$thu$q$, $q$7:00 pm$q$, $q$7:15 pm$q$, $q$Build the Tent challenge$q$, $q$Program$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "game", "summary": "Two teams or two people race to build the tents. Mike connects the activity to Isaiah 54:2 and the need for vision, preparation, and teamwork."}$q$::jsonb, $q${"purpose": "Two teams or two people race to build the tents. Mike connects the activity to Isaiah 54:2 and the need for vision, preparation, and teamwork.", "owner": "Mike", "support": "Mike, Ryan and Brooke", "category": "program", "materials": "Two tents, timer, Expand the Tent sign", "notes": "First illustration. Keep one inside and one outside if space allows."}$q$::jsonb, 20, false),
  ('b1f0a5d2-0f4a-4b1e-9c1a-2d5f3a7c9103'::uuid, $q$thu$q$, $q$7:15 pm$q$, $q$7:30 pm$q$, $q$Worship$q$, $q$Program$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "worship", "summary": "Turn attention toward God and the weekend theme."}$q$::jsonb, $q${"purpose": "Turn attention toward God and the weekend theme.", "owner": "JonCarlos", "support": "Scott audio; Junior AV and coverage", "category": "program", "materials": "Microphones, lyrics, instruments", "notes": "Ryan hands off from the tent illustration and introduces worship."}$q$::jsonb, 21, false),
  ('b1f0a5d2-0f4a-4b1e-9c1a-2d5f3a7c9104'::uuid, $q$thu$q$, $q$7:30 pm$q$, $q$8:30 pm$q$, $q$Teaching and vision$q$, $q$Program$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "program", "summary": "Sammy and Suzanne welcome everyone and frame the weekend.", "title": "Teaching and vision: Sammy and Suzanne"}$q$::jsonb, $q${"purpose": "Sammy and Suzanne welcome the group and frame the weekend around what God is doing through Shine.", "owner": "Sammy and Suzanne", "support": "Ryan transition; Junior coverage", "category": "program", "materials": "Teaching notes, theme Scripture", "notes": "Tent remains visible as the theme prop."}$q$::jsonb, 22, false),
  ('b1f0a5d2-0f4a-4b1e-9c1a-2d5f3a7c9105'::uuid, $q$thu$q$, $q$8:30 pm$q$, $q$10:00 pm$q$, $q$Fellowship$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "social", "summary": "Unhurried time together."}$q$::jsonb, $q${"purpose": "Provide unhurried relationship time with snacks and drinks.", "owner": "Brooke", "support": "Emma, Ryan and Brooke", "category": "operations", "materials": "Snacks, drinks", "notes": "Reset snack station and announce Friday breakfast."}$q$::jsonb, 23, true),
  ('98992a00-9a21-48ec-8b68-9a14aac8e3ff'::uuid, $q$fri$q$, $q$8:00 am$q$, $q$8:45 am$q$, $q$Breakfast and coffee$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "meal", "menu": ["Egg and sausage bake", "Fresh English muffin toast", "Homemade apple butter", "Cut-up mixed fresh fruit", "Freshly brewed coffee from The Dock Coffee", "Orange juice"], "title": "Breakfast", "summary": "Serve breakfast and provide relaxed connection time."}$q$::jsonb, $q${"purpose": "Serve breakfast and provide relaxed connection time.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Egg and sausage bake, toast, fruit, coffee", "notes": "Sammy to determine who will bless the meal."}$q$::jsonb, 24, true),
  ('1784c511-d071-5762-9b7b-762846e270f4'::uuid, $q$fri$q$, $q$8:45 am$q$, $q$9:00 am$q$, $q$Breakfast cleanup and worship transition$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Clear breakfast, tidy common areas, and give a five-minute call to worship (Mike).", "owner": "Keta", "support": "Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup supplies", "notes": "Quietly finish remaining cleanup after worship begins if needed."}$q$::jsonb, 25, true),
  ('86b0ec99-8fce-444a-990e-b44837ef88d5'::uuid, $q$fri$q$, $q$9:00 am$q$, $q$9:20 am$q$, $q$Worship$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "worship", "summary": "Begin the day centered on God."}$q$::jsonb, $q${"purpose": "Begin the day centered on God.", "owner": "JonCarlos", "support": "Scott audio; Junior AV and coverage", "category": "program", "materials": "Worship setup", "notes": "Hand off to Tito."}$q$::jsonb, 26, false),
  ('c6c6dabc-a9cf-42ef-b5f1-01c194251f6c'::uuid, $q$fri$q$, $q$9:20 am$q$, $q$9:30 am$q$, $q$Devotional$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "title": "Devotional: Tito", "summary": "Short devotional preparing hearts for the morning."}$q$::jsonb, $q${"purpose": "Short devotional preparing hearts for the morning.", "owner": "Tito", "support": "Junior coverage", "category": "program", "materials": "Bible and notes", "notes": "Hand off to Mike and Victor."}$q$::jsonb, 27, false),
  ('ecad74c7-cf11-42b1-b171-05aad9563850'::uuid, $q$fri$q$, $q$9:30 am$q$, $q$10:15 am$q$, $q$Gusii Land recap$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "summary": "The story of God's work and impact.", "title": "Gusii Land recap: Mike and Victor"}$q$::jsonb, $q${"purpose": "Share the story of God's work and impact through Mike, Victor, photos, and video.", "owner": "Mike and Victor", "support": "Junior AV and coverage", "category": "program", "materials": "Slides, photos, video", "notes": "Ryan announces break."}$q$::jsonb, 28, false),
  ('955e25bf-6e62-4af1-b6ff-c63485d89af1'::uuid, $q$fri$q$, $q$10:15 am$q$, $q$10:30 am$q$, $q$Coffee break and rope prep$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "break", "opens": ["coffee"], "summary": "The coffee bar is open.", "title": "Break"}$q$::jsonb, $q${"purpose": "Coffee bar and water, and confirm every chair has rope.", "owner": "Brooke and Ryan", "support": "Scott", "category": "operations", "materials": "Coffee, water, rope, knot sample", "notes": "Mike and helpers take positions."}$q$::jsonb, 29, true),
  ('937d12aa-aef3-499e-827a-36c180787006'::uuid, $q$fri$q$, $q$10:30 am$q$, $q$11:25 am$q$, $q$Shine What's Next and Lengthen the Cords$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "summary": "Includes the Lengthen the Cords illustration.", "title": "SHINE What's Next: Mike"}$q$::jsonb, $q${"purpose": "Share Shine's next steps. Guests connect individual ropes into one long cord, showing how relationships extend the mission's reach.", "owner": "Mike", "support": "Mike, Ryan and Brooke", "category": "program", "materials": "Precut rope, knot sample, Scripture slide", "notes": "Second illustration. Display the connected cord with the tent."}$q$::jsonb, 30, false),
  ('2c7f67e3-6f5d-4da4-98b9-c72586f89459'::uuid, $q$fri$q$, $q$11:30 am$q$, $q$12:00 pm$q$, $q$Word from Sammy and Suzanne$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "title": "Word from Sammy and Suzanne on SHINE What's Next", "summary": "Respond spiritually to what Shine is becoming and prepare guests for the rest of the weekend."}$q$::jsonb, $q${"purpose": "Respond spiritually to what Shine is becoming and prepare guests for the rest of the weekend.", "owner": "Sammy and Suzanne", "support": "Ryan transition; Junior coverage", "category": "program", "materials": "Teaching notes", "notes": "Release to lunch."}$q$::jsonb, 31, false),
  ('9359a475-11ad-5e75-adec-146d1f912d14'::uuid, $q$fri$q$, $q$11:30 am$q$, $q$12:00 pm$q$, $q$Morning bathroom cleaning (during session)$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Wipe countertops and mirrors, clean toilets, fill toiletries.", "owner": "Alice", "support": "Scott", "category": "operations"}$q$::jsonb, 32, true),
  ('8c658bb2-d05c-4db9-b514-babc9bfdc251'::uuid, $q$fri$q$, $q$12:00 pm$q$, $q$1:00 pm$q$, $q$Lunch$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "meal", "menu": ["Build-your-own fresh-baked croissant sandwiches: ham, turkey, provolone and cheddar, lettuce, sliced tomatoes, mayonnaise and butter", "House-made hearty chicken wild rice soup with soda crackers", "Bistro kettle chips", "Assorted cookies"], "summary": "Serve lunch and encourage table conversation."}$q$::jsonb, $q${"purpose": "Serve lunch and encourage table conversation.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Croissant sandwich bar, soup, cookies", "notes": "Explain free-time options. Sammy to determine who will bless the meal."}$q$::jsonb, 33, true),
  ('aedb0bd2-e8ba-5ce7-950a-b171bbf6341b'::uuid, $q$fri$q$, $q$12:45 pm$q$, $q$1:15 pm$q$, $q$Lunch cleanup$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Clear food, wash serving items, wipe stations, and reset kitchen and snack areas.", "owner": "Keta", "support": "Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup supplies", "notes": "Work quietly as free time begins."}$q$::jsonb, 34, true),
  ('98dc6592-07ac-4a22-bc56-e3c414be1a9b'::uuid, $q$fri$q$, $q$1:00 pm$q$, $q$4:00 pm$q$, $q$Free time$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "free", "opens": ["activities"], "summary": "Rest and time together. See everything the property offers."}$q$::jsonb, $q${"purpose": "Protect rest, conversations, and informal relationships.", "owner": "Brooke and Ryan", "support": "As needed", "category": "operations", "materials": "Activity menu"}$q$::jsonb, 35, true),
  ('2aaf68f7-a148-59d0-8e65-df8da9f55196'::uuid, $q$fri$q$, $q$1:00 pm$q$, $q$2:00 pm$q$, $q$Bingo prep$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Head to where bingo will be hosted, and set up prizes.", "owner": "Brooke", "support": "Keta and Emma", "category": "operations", "materials": "Tables, decorations and prizes"}$q$::jsonb, 36, true),
  ('995c6b13-6c34-421a-8c36-d138aeb9459c'::uuid, $q$fri$q$, $q$2:00 pm$q$, $q$4:00 pm$q$, $q$Wanyonyi favorite-things bingo$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "game", "summary": "A personalized game to celebrate and connect. Optional: free time and activities stay open.", "optional": true, "title": "Bingo of Wanyonyi's favorite things"}$q$::jsonb, $q${"purpose": "Lead the personalized bingo game and distribute ranked prizes.", "owner": "Brooke", "support": "Keta and Emma", "category": "operations", "materials": "Bingo cards, small, medium and large prizes"}$q$::jsonb, 37, true),
  ('07a7520c-a962-5ba6-ba9c-d57a09bfbd21'::uuid, $q$fri$q$, $q$4:00 pm$q$, $q$4:30 pm$q$, $q$Bingo clean-up$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Tear down and prep.", "owner": "Brooke", "support": "Keta and Emma", "category": "operations", "materials": "Pack up and clean"}$q$::jsonb, 38, true),
  ('b541af80-0cb2-478a-b6a3-135c1b140058'::uuid, $q$fri$q$, $q$4:00 pm$q$, $q$5:00 pm$q$, $q$Free time and open coffee bar$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "coffee", "opens": ["coffee"], "summary": "Free time continues and the coffee bar is open.", "title": "Open coffee bar"}$q$::jsonb, $q${"purpose": "Offer espresso drinks, snacks, conversation, and rest.", "owner": "Ryan and Parker", "support": "Emma, Ryan and Brooke", "category": "operations", "materials": "Espresso and snack supplies", "notes": "Keta cleans bathrooms during this block.", "confirm": "assignment"}$q$::jsonb, 39, true),
  ('fed52e02-9606-4d78-93ec-5e6254b905f6'::uuid, $q$fri$q$, $q$5:00 pm$q$, $q$5:30 pm$q$, $q$Dinner preparation and personal reset$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "break", "title": "Get ready for dinner", "summary": "Set tables, meal delivery, light candles, and invite guests to get ready."}$q$::jsonb, $q${"purpose": "Set tables, meal delivery, light candles, and invite guests to get ready.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Table settings"}$q$::jsonb, 40, true),
  ('761ace4d-76eb-41c1-a90c-7687d0783737'::uuid, $q$fri$q$, $q$5:30 pm$q$, $q$6:30 pm$q$, $q$Dinner$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "meal", "menu": ["Signature smoked brisket, carved by our staff", "Baked potato with butter and sour cream, or garlic baby reds instead", "Hot honey Brussels sprouts with bacon", "House-made coleslaw", "Warm dinner rolls with soft butter", "Apple crisp with house-made whipped cream"], "summary": "Serve brisket dinner and dessert."}$q$::jsonb, $q${"purpose": "Serve brisket dinner and dessert.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Catered dinner and dessert", "notes": "Sammy to determine who will bless the meal."}$q$::jsonb, 41, true),
  ('d50d6582-c06a-4554-a9e8-2a49a7107a70'::uuid, $q$fri$q$, $q$6:30 pm$q$, $q$7:00 pm$q$, $q$Dinner cleanup and worship reset$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "break", "title": "Get ready for worship", "summary": "Clear dinner, reset main room, and check AV and microphones."}$q$::jsonb, $q${"purpose": "Clear dinner, reset main room, and check AV and microphones.", "owner": "Keta", "support": "Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup and AV supplies", "notes": "Worship team ready by 6:55 PM."}$q$::jsonb, 42, true),
  ('5333508a-14cd-55da-9c71-2358f63b88e8'::uuid, $q$fri$q$, $q$7:00 pm$q$, $q$7:50 pm$q$, $q$Worship$q$, $q$Program$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "worship", "summary": "Lead the group in evening worship."}$q$::jsonb, $q${"purpose": "Lead the group in evening worship.", "owner": "JonCarlos", "support": "Scott audio; Junior AV and coverage", "category": "program", "materials": "Worship setup", "notes": "Hand off to Rev. Canana."}$q$::jsonb, 43, false),
  ('752801c2-1d94-4ecd-9358-b479f14e3ff5'::uuid, $q$fri$q$, $q$7:50 pm$q$, $q$8:30 pm$q$, $q$Impact with Rev. Canana and videos$q$, $q$Program$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "program", "summary": "Stories and videos of changed lives.", "title": "Impact: Rev. Canana and videos"}$q$::jsonb, $q${"purpose": "Connect guests to lives changed through testimony and selected videos.", "owner": "Rev. Canana", "support": "Ryan transition; Junior AV and coverage", "category": "program", "materials": "Video files, microphones", "notes": "Move into fellowship."}$q$::jsonb, 44, false),
  ('90632a71-b71e-58f1-b8e4-6bade98ba802'::uuid, $q$fri$q$, $q$8:00 pm$q$, $q$8:30 pm$q$, $q$Late-afternoon bathroom cleaning$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Clean and restock all event bathrooms before dinner.", "owner": "Keta", "support": "Emma", "category": "operations", "materials": "Cleaning and restroom supplies", "notes": "The source labels this late afternoon and says before dinner, but times it 8:00 to 8:30 PM.", "confirm": "time"}$q$::jsonb, 45, true),
  ('9bd57c44-9faf-5ebc-aeec-526563bee931'::uuid, $q$fri$q$, $q$8:15 pm$q$, $q$8:30 pm$q$, $q$Bonfire and fellowship setup$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Light and monitor bonfire; set out candy, movies, and snacks before the program.", "owner": "Scott", "support": "Scott and snack team", "category": "operations", "materials": "Fire supplies, movies, candy, snacks"}$q$::jsonb, 46, true),
  ('d951b5ec-e0fa-4279-86e7-be1ddc99ef54'::uuid, $q$fri$q$, $q$8:30 pm$q$, $q$10:30 pm$q$, $q$Fellowship, bonfire and movies$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "social", "summary": "Bonfire, arcade and movies with candy.", "title": "Fellowship"}$q$::jsonb, $q${"purpose": "Close with relaxed conversation, arcade, candy, movies, and bonfire.", "owner": "Scott and Brooke", "support": "Scott; Emma, Ryan and Brooke", "category": "operations", "materials": "Fire and fellowship supplies", "notes": "Junior captures selected moments; announce Saturday breakfast."}$q$::jsonb, 47, true),
  ('f752c677-c595-5167-9585-18cd42a88595'::uuid, $q$sat$q$, $q$7:30 am$q$, $q$8:00 am$q$, $q$Morning readiness$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Check bathrooms, light candles, check snack station.", "owner": "Brooke", "support": "Emma and Scott bathrooms; Keta and Emma stakes; Ryan hospitality", "category": "operations", "materials": "Cleaning supplies, coffee, prepared stakes", "notes": "Complete before guests gather."}$q$::jsonb, 48, true),
  ('514d14f4-14ec-423f-acba-e6da7d1df9c3'::uuid, $q$sat$q$, $q$8:00 am$q$, $q$8:45 am$q$, $q$Breakfast and coffee$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "meal", "menu": ["Sausage gravy and biscuits", "House-made cheese and sun-dried tomato quiche", "Cut-up mixed fresh fruit", "Coffee and orange juice"], "title": "Breakfast", "summary": "Serve breakfast and provide connection time."}$q$::jsonb, $q${"purpose": "Serve breakfast and provide connection time.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Biscuits and gravy, quiche, fruit, coffee", "notes": "Sammy to determine who will bless the meal."}$q$::jsonb, 49, true),
  ('5e61315c-9fff-5efa-814c-0d76565ac36f'::uuid, $q$sat$q$, $q$8:45 am$q$, $q$9:00 am$q$, $q$Breakfast cleanup and worship transition$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Clear breakfast, tidy common areas, and give a five-minute call to worship (Mike).", "owner": "Keta", "support": "Brooke, Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup supplies"}$q$::jsonb, 50, true),
  ('644f01ec-3774-45e8-b91f-e2035184e972'::uuid, $q$sat$q$, $q$9:00 am$q$, $q$9:20 am$q$, $q$Worship$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "worship", "summary": "Begin the day centered on God."}$q$::jsonb, $q${"purpose": "Begin the day centered on God.", "owner": "JonCarlos", "support": "Scott audio; Junior AV and coverage", "category": "program", "materials": "Worship setup", "notes": "Hand off to devotional leader."}$q$::jsonb, 51, false),
  ('e480befc-8182-460f-84bf-4f0459d16d9b'::uuid, $q$sat$q$, $q$9:20 am$q$, $q$9:30 am$q$, $q$Devotional$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "summary": "Short devotional preparing hearts for vision and response."}$q$::jsonb, $q${"purpose": "Short devotional preparing hearts for vision and response.", "owner": "Tito", "support": "Junior AV and coverage", "category": "program", "materials": "Bible and notes", "notes": "The source lists Tito and still notes that the owner needs confirmation.", "confirm": "assignment"}$q$::jsonb, 52, false),
  ('1be2ec84-8cef-4184-8090-8016bab25052'::uuid, $q$sat$q$, $q$9:30 am$q$, $q$10:15 am$q$, $q$Impact stories$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "summary": "Stories of transformation."}$q$::jsonb, $q${"purpose": "Share concise stories of transformation with selected media.", "owner": "Mike and Sammy", "support": "Junior AV and coverage", "category": "program", "materials": "Microphones, selected video", "notes": "Mike may use optional hula-hoop relay only if energy is low."}$q$::jsonb, 53, false),
  ('1d8a351a-a33e-481c-9f51-3027e5b06364'::uuid, $q$sat$q$, $q$10:15 am$q$, $q$10:30 am$q$, $q$Break and message reset$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "break", "opens": ["coffee"], "summary": "The coffee bar is open.", "title": "Break"}$q$::jsonb, $q${"purpose": "Coffee bar and water, prepare Sammy's presentation and tent and cord visuals.", "owner": "Ryan and Brooke", "support": "Snack station team; Junior AV", "category": "operations", "materials": "Coffee, water, presentation, visual props"}$q$::jsonb, 54, true),
  ('c8d8cc63-b1a4-4ae9-819a-5786a9370f43'::uuid, $q$sat$q$, $q$10:30 am$q$, $q$11:30 am$q$, $q$Sammy big vision message$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "summary": "The central vision for SHINE's future."}$q$::jsonb, $q${"purpose": "Cast the central vision for Shine's future using the weekend's tent and cord imagery.", "owner": "Sammy", "support": "Ryan transition; Junior AV and coverage", "category": "program", "materials": "Presentation, Scripture, tent and cord visuals", "notes": "Move into partner invitation."}$q$::jsonb, 55, false),
  ('96af7544-c551-4cd0-b794-8b9aeefa5ef5'::uuid, $q$sat$q$, $q$11:30 am$q$, $q$12:00 pm$q$, $q$Partner invitation and Strengthen the Stakes$q$, $q$Program$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "program", "title": "Partner invitation", "summary": "Explain next faithful steps. Guests add their name and personal takeaway to the stake and take it home."}$q$::jsonb, $q${"purpose": "Explain next faithful steps. Guests add their name and personal takeaway to the stake and take it home.", "owner": "Mike and Sammy", "support": "Mike, Ryan, Brooke and prayer team", "category": "program", "materials": "Four-sided stakes, Sharpies, giving information, quiet music", "notes": "Final illustration; invitation remains prayerful and without public pressure."}$q$::jsonb, 56, false),
  ('182f2cc0-f08a-5465-abf3-a25689e7ab90'::uuid, $q$sat$q$, $q$11:30 am$q$, $q$12:00 pm$q$, $q$Morning bathroom cleaning (during session)$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Wipe countertops and mirrors, clean toilets, fill toiletries.", "owner": "Alice", "support": "Scott", "category": "operations"}$q$::jsonb, 57, true),
  ('ebb5c598-57ce-4c1e-be22-fd23ddfb5b86'::uuid, $q$sat$q$, $q$12:00 pm$q$, $q$1:00 pm$q$, $q$Lunch$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "meal", "menu": ["Ultimate salad bar with fresh chopped romaine and a choice of 8 salad toppings", "House-made ranch, French and vinaigrette", "Italian beef slider sandwiches with warm au jus", "Assorted bars"], "summary": "Serve lunch and allow conversation after the response. Mike explains the prayer walk."}$q$::jsonb, $q${"purpose": "Serve lunch and allow conversation after the response. Mike explains the prayer walk.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Ultimate salad bar and sandwiches", "notes": "Explain prayer walk and free time. Sammy to determine who will bless the meal."}$q$::jsonb, 58, true),
  ('f95df53a-21c2-563d-986c-a12851a356e3'::uuid, $q$sat$q$, $q$12:45 pm$q$, $q$1:00 pm$q$, $q$Lunch cleanup$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Clear food and reset dining, kitchen, and snack areas.", "owner": "Keta", "support": "Alice, Keta, Emma and Scott", "category": "operations", "materials": "Cleanup supplies"}$q$::jsonb, 59, true),
  ('56aa5c99-767d-4281-988c-8be40de8e17e'::uuid, $q$sat$q$, $q$1:00 pm$q$, $q$4:00 pm$q$, $q$Free time$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "free", "opens": ["activities"], "summary": "Rest and time together, including the lakefront prayer walk."}$q$::jsonb, $q${"purpose": "Protect rest, prayer, and meaningful conversations.", "owner": "Brooke and Ryan", "support": "As needed", "category": "operations"}$q$::jsonb, 60, true),
  ('9958510d-4084-5e71-a153-53934a27b3b8'::uuid, $q$sat$q$, $q$1:00 pm$q$, $q$2:00 pm$q$, $q$Prayer walk$q$, $q$Program$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "program", "optional": true, "summary": "Prayer walk."}$q$::jsonb, $q${"purpose": "Prayer walk.", "owner": "Scott", "support": "As needed", "category": "program", "materials": "Prayer prompts and maps"}$q$::jsonb, 61, false),
  ('01ef3098-10f7-5c1f-9438-608b0c1c3639'::uuid, $q$sat$q$, $q$1:00 pm$q$, $q$2:00 pm$q$, $q$Setup cornhole$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Set up cornhole and prizes.", "owner": "Brooke", "support": "Keta and Emma", "category": "operations"}$q$::jsonb, 62, true),
  ('851edeef-b4db-4c29-9001-a6bc677151f9'::uuid, $q$sat$q$, $q$2:00 pm$q$, $q$4:00 pm$q$, $q$Cornhole tournament$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "game", "summary": "A playful team tournament. Optional: free time and activities stay open.", "optional": true}$q$::jsonb, $q${"purpose": "Lead a lighthearted tournament and maintain guest engagement.", "owner": "Brooke", "support": "Keta and Emma", "category": "operations", "materials": "Cornhole sets and bracket", "notes": "Use indoor game backup if weather requires."}$q$::jsonb, 63, true),
  ('74fb6d2a-46ae-4dcf-8061-c923dd6b5e32'::uuid, $q$sat$q$, $q$4:00 pm$q$, $q$5:00 pm$q$, $q$Open coffee bar$q$, $q$Operations$q$, $q$everyone$q$, $q$afternoon$q$, $q${"kind": "coffee", "opens": ["coffee"], "summary": "Free time continues and the coffee bar is open."}$q$::jsonb, $q${"purpose": "Offer espresso drinks, snacks, rest, and conversation.", "owner": "Ryan", "support": "Parker", "category": "operations", "materials": "Espresso and snack supplies"}$q$::jsonb, 64, true),
  ('5d21d636-e85f-51d7-a446-57929c40d6e1'::uuid, $q$sat$q$, $q$4:15 pm$q$, $q$4:45 pm$q$, $q$Late-afternoon bathroom cleaning$q$, $q$Operations$q$, $q$planner$q$, $q$afternoon$q$, null::jsonb, $q${"purpose": "Clean and restock all event bathrooms before dinner.", "owner": "Keta", "support": "Emma", "category": "operations", "materials": "Cleaning and restroom supplies"}$q$::jsonb, 65, true),
  ('a2b853ea-44d7-4dbe-a99b-ca1ae8e38e92'::uuid, $q$sat$q$, $q$5:00 pm$q$, $q$5:30 pm$q$, $q$Celebration preparation and personal reset$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "break", "title": "Get ready for the celebration", "summary": "Set tables, light candles, check meal delivery, prepare bonfire and celebration supplies, and invite guests to get ready (Mike)."}$q$::jsonb, $q${"purpose": "Set tables, light candles, check meal delivery, prepare bonfire and celebration supplies, and invite guests to get ready (Mike).", "owner": "Brooke", "support": "Catering Team; Scott, Keta, Emma, Alice, Ryan", "category": "operations", "materials": "Table settings, fire and glow celebration setup"}$q$::jsonb, 66, true),
  ('1b2e2eaa-61e6-464d-9cd3-5193e65af702'::uuid, $q$sat$q$, $q$5:30 pm$q$, $q$6:30 pm$q$, $q$Celebration dinner$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"kind": "meal", "menu": ["Smoked half chicken ribs", "Yukon gold mashed potatoes and gravy", "Chef's choice seasonal green vegetable", "Southwest black bean and corn salad", "Warm dinner rolls with soft butter", "Pumpkin cheesecake"], "title": "Dinner", "summary": "Celebrate God's faithfulness together over dinner."}$q$::jsonb, $q${"purpose": "Celebrate God's faithfulness together over dinner.", "owner": "Brooke", "support": "Catering Team", "category": "operations", "materials": "Chicken dinner and pumpkin cheesecake", "notes": "Sammy to determine who will bless the meal."}$q$::jsonb, 67, true),
  ('106db345-660d-4c20-addc-0596569499d0'::uuid, $q$sat$q$, $q$6:30 pm$q$, $q$7:00 pm$q$, $q$Dinner cleanup and celebration setup$q$, $q$Operations$q$, $q$planner$q$, $q$evening$q$, null::jsonb, $q${"purpose": "Clear dinner, activate evening stations, prepare bonfires, games, desserts, and glow materials.", "owner": "Keta and Scott", "support": "Alice, Keta, Emma, Scott, Ryan and Brooke", "category": "operations", "materials": "Cleanup, fire, dessert, game and glow supplies", "notes": "Glow walk and run."}$q$::jsonb, 68, true),
  ('eb513b79-1a91-4c48-9663-c890ce38c3a0'::uuid, $q$sat$q$, $q$7:00 pm$q$, $q$10:30 pm$q$, $q$Celebration evening$q$, $q$Operations$q$, $q$everyone$q$, $q$evening$q$, $q${"tbc": "An optional glow walk or run is still to be confirmed.", "kind": "social", "summary": "Bonfires, games, desserts and an ice cream social.", "title": "Celebration: bonfires, games and desserts"}$q$::jsonb, $q${"purpose": "Bonfires, games, music, desserts, and optional glow walk or run.", "owner": "Brooke and Ryan", "support": "Scott, Keta, Emma, Alice; Junior coverage", "category": "operations", "materials": "Handout glow supplies", "notes": "Close informally and announce Sunday departure plan (Mike)."}$q$::jsonb, 69, true),
  ('2f7b0b5b-1d66-511f-a25b-b98d9fc7ac6e'::uuid, $q$sun$q$, $q$7:00 am$q$, $q$7:30 am$q$, $q$Departure morning readiness$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Start coffee, set grab-and-go breakfast, open packing areas, and prepare checkout.", "owner": "Brooke", "support": "Hospitality team", "category": "operations", "materials": "Breakfast, coffee, to-go supplies, checkout list", "notes": "No formal Sunday program."}$q$::jsonb, 70, true),
  ('1011d13c-09af-46b0-a9ad-2ea4a6252631'::uuid, $q$sun$q$, $q$7:30 am$q$, $q$8:30 am$q$, $q$Grab-and-go breakfast$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "meal", "menu": ["Spinach and feta breakfast pastry", "Assorted scratch-made scones and muffins", "Whole fresh fruit or individual mixed fruit cups", "Individual premade yogurt parfaits", "Orange juice and coffee", "To-go containers and cups"], "summary": "Grab-and-go while you pack."}$q$::jsonb, $q${"purpose": "Provide simple hospitality while guests pack and load.", "owner": "Brooke", "support": "Hospitality team", "category": "operations", "materials": "Pastries, muffins, fruit, coffee, to-go cups"}$q$::jsonb, 71, true),
  ('8165e90e-8d87-48f7-8d6f-261862e77028'::uuid, $q$sun$q$, $q$8:30 am$q$, $q$9:00 am$q$, $q$Pack, checkout and guest departures$q$, $q$Operations$q$, $q$everyone$q$, $q$morning$q$, $q${"kind": "break", "summary": "No program on Sunday. Load up, check out and head home.", "title": "Pack, checkout and departures"}$q$::jsonb, $q${"purpose": "Help load vehicles, check rooms, collect lost-and-found, and say goodbye.", "owner": "Brooke and Ryan", "support": "All available team", "category": "operations", "materials": "Checkout list, room checklist, lost-and-found bin", "notes": "Junior captures selected closing moments."}$q$::jsonb, 72, true),
  ('214fc4a1-f7e1-5ec7-99c0-5faf36bd525a'::uuid, $q$sun$q$, $q$8:30 am$q$, $q$9:00 am$q$, $q$Breakfast cleanup and snack station pack$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Clear breakfast, pack food and coffee supplies, and pack the snack station.", "owner": "Keta and Emma", "support": "Alice, Keta, Emma, Scott, Ryan and Brooke", "category": "operations", "materials": "Cleanup and packing supplies"}$q$::jsonb, 73, true),
  ('ccf99f87-52fe-55f2-8cae-13582ec9fe3c'::uuid, $q$sun$q$, $q$9:00 am$q$, $q$10:00 am$q$, $q$Pack production and program materials$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Pack speakers, AV, tents, cords, remaining stakes, signage, games, and display materials.", "owner": "Junior and Scott", "support": "Junior, Scott, Mike, Ryan and Brooke", "category": "operations", "materials": "Packing labels and equipment cases", "notes": "Scott packs speakers; Junior packs AV."}$q$::jsonb, 74, true),
  ('67cc1d3b-107c-480f-aeb7-fc45dd812e3c'::uuid, $q$sun$q$, $q$9:30 am$q$, $q$10:00 am$q$, $q$Final cleanup and house reset$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Reset guest rooms, bathrooms, kitchen, common areas, exterior spaces, trash, and supplies.", "owner": "Brooke", "support": "Remaining team", "category": "operations", "materials": "Final reset checklist", "notes": "Assign zones before the weekend."}$q$::jsonb, 75, true),
  ('a1082a68-a431-56fc-b48b-a60ff875c0b4'::uuid, $q$sun$q$, $q$9:30 am$q$, $q$10:00 pm$q$, $q$Final property walkthrough and team departure$q$, $q$Operations$q$, $q$planner$q$, $q$morning$q$, null::jsonb, $q${"purpose": "Check every room, gather lost-and-found, confirm nothing remains, and pray.", "owner": "Brooke and Ryan", "support": "Remaining team", "category": "operations", "materials": "Master checklist, keys", "notes": "The source times this 9:30 AM to 10:00 PM, while the surrounding rows are morning.", "confirm": "time"}$q$::jsonb, 76, true);

select count(*) into expected from master;
if expected <> 77 then
  raise exception 'master: expected 77 rows, got %', expected;
end if;

/* Keep a copy of everything the master does not name, then retire it from the
   working views in one step so no stale row or assignment is left behind. */
insert into public.schedule_items_archive (id, engagement_id, snapshot)
select s.id, s.engagement_id, to_jsonb(s)
  from public.schedule_items s
 where s.engagement_id = shine
   and s.id not in (select id from master)
on conflict (id) do nothing;

delete from public.tasks
 where engagement_id = shine
   and schedule_item_id is not null
   and schedule_item_id not in (select id from master);

delete from public.schedule_item_ops
 where engagement_id = shine
   and schedule_item_id not in (select id from master);

delete from public.schedule_items
 where engagement_id = shine
   and id not in (select id from master);

insert into public.schedule_items
  (id, engagement_id, day_key, starts_label, ends_label, title, track,
   audience, daypart, status, guest_guide, position)
select m.id, shine, m.day_key, m.starts_label, m.ends_label, m.title, m.track,
       m.audience, m.daypart, 'confirmed', m.guest_guide, m.position
  from master m
on conflict (id) do update
   set day_key = excluded.day_key,
       starts_label = excluded.starts_label,
       ends_label = excluded.ends_label,
       title = excluded.title,
       track = excluded.track,
       audience = excluded.audience,
       daypart = excluded.daypart,
       status = 'confirmed',
       guest_guide = excluded.guest_guide,
       position = excluded.position;

select count(*) into found from public.schedule_items where engagement_id = shine;
if found <> expected then
  raise exception 'schedule: expected % rows, found %', expected, found;
end if;

insert into public.schedule_item_ops (schedule_item_id, engagement_id, detail)
select m.id, shine, m.ops from master m
on conflict (schedule_item_id) do update
   set detail = excluded.detail, updated_at = now();

/* Day-of duties are regenerated from the master. Pre-event tasks, which the
   master does not describe, are untouched. Nothing is marked done. */
delete from public.tasks
 where engagement_id = shine
   and coalesce(duty->>'phase', '') <> 'before';

insert into public.tasks
  (engagement_id, title, status, owner_name, schedule_item_id, duty)
select shine, m.title, 'todo', m.ops->>'owner', m.id,
       jsonb_build_object('phase', m.day_key, 'order', m.position,
                          'when', m.starts_label, 'fromMaster', true)
  from master m
 where m.is_duty;

select count(*) into found from public.tasks
 where engagement_id = shine and coalesce(duty->>'phase', '') = 'before';
if found < 14 then
  raise exception 'pre-event tasks: expected at least 14, found %', found;
end if;

if exists (select 1 from public.schedule_items
            where engagement_id = shine and title ~* 'wanyoni(?!yi)') then
  raise exception 'a misspelling remains';
end if;

end $migration$;
